/*

Testing ResourcesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_ResourcesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ResourcesAPIService CreateResource", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var resourceGroup string
		var kind string
		var namespace string

		resp, httpRes, err := apiClient.ResourcesAPI.CreateResource(context.Background(), resourceGroup, kind, namespace).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ResourcesAPIService DeleteResource", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var resourceGroup string
		var kind string
		var namespace string
		var name string

		httpRes, err := apiClient.ResourcesAPI.DeleteResource(context.Background(), resourceGroup, kind, namespace, name).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ResourcesAPIService GetResource", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var resourceGroup string
		var kind string
		var namespace string
		var name string

		resp, httpRes, err := apiClient.ResourcesAPI.GetResource(context.Background(), resourceGroup, kind, namespace, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ResourcesAPIService ListResources", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ResourcesAPI.ListResources(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ResourcesAPIService UpdateResource", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var resourceGroup string
		var kind string
		var namespace string
		var name string

		resp, httpRes, err := apiClient.ResourcesAPI.UpdateResource(context.Background(), resourceGroup, kind, namespace, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ResourcesAPIService UpdateResourceStatus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var resourceGroup string
		var kind string
		var namespace string
		var name string

		resp, httpRes, err := apiClient.ResourcesAPI.UpdateResourceStatus(context.Background(), resourceGroup, kind, namespace, name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
