// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/groups/{resource_group}/namespaces/{namespace}/kinds/{kind}/resources": {
            "post": {
                "description": "Creates a new resource with the provided details.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resources"
                ],
                "summary": "Create a new resource",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Resource Group",
                        "name": "resource_group",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Namespace",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Resource details",
                        "name": "resource",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.ResourceCreateOpts"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "body": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Resource created\" example={\"id\":1,\"resource_group\":\"group1\",\"kind\":\"type1\",\"namespace\":\"ns1\",\"name\":\"resource1\",\"shard_id\":\"default\",\"body\":{\"key\":\"value\"},\"labels\":{\"env\":\"prod\"},\"created_at\":\"2025-05-12T00:00:00Z\",\"updated_at\":\"2025-05-12T00:00:00Z\",\"version\":1,\"current_version\":0}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.Resource"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "body": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid input\" example={\"error\":\"Validation failed: shard_id is required\"}",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error\" example={\"error\":\"Failed to create resource: database error\"}",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/groups/{resource_group}/namespaces/{namespace}/kinds/{kind}/resources/{name}": {
            "get": {
                "description": "Retrieves a resource by its resource_group, kind, namespace, and name.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resources"
                ],
                "summary": "Get a resource by key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Resource Group",
                        "name": "resource_group",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Namespace",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Resource found\" example={\"id\":1,\"resource_group\":\"group1\",\"kind\":\"type1\",\"namespace\":\"ns1\",\"name\":\"resource1\",\"shard_id\":\"default\",\"body\":{\"key\":\"value\"},\"labels\":{\"env\":\"prod\"},\"created_at\":\"2025-05-12T00:00:00Z\",\"updated_at\":\"2025-05-12T00:00:00Z\",\"version\":1,\"current_version\":0}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.Resource"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "body": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid input\" example={\"error\":\"Validation failed: resource_group is required\"}",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found\" example={\"error\":\"Resource not found: no rows\"}",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates a resource with the provided details.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resources"
                ],
                "summary": "Update a resource",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Resource Group",
                        "name": "resource_group",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Kind",
                        "name": "kind",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Namespace",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Resource details",
                        "name": "resource",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.ResourceUpdateOpts"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "body": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "object",
                                                "additionalProperties": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Resource updated\" example={\"id\":1,\"resource_group\":\"group1\",\"kind\":\"type1\",\"namespace\":\"ns1\",\"name\":\"resource1\",\"shard_id\":\"default\",\"body\":{\"key\":\"new_value\"},\"labels\":{\"env\":\"dev\"},\"created_at\":\"2025-05-12T00:00:00Z\",\"updated_at\":\"2025-05-12T01:00:00Z\",\"version\":2,\"current_version\":0}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.Resource"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "body": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid input\" example={\"error\":\"Validation failed: shard_id is required\"}",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error\" example={\"error\":\"Failed to update resource: database error\"}",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/resources": {
            "get": {
                "description": "возвращает ресурсы по фильтру",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resources"
                ],
                "summary": "List pending resources",
                "parameters": [
                    {
                        "type": "string",
                        "name": "kind",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "namespace",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "name": "pending",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "resource_group",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "shard_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of pending resources",
                        "schema": {
                            "type": "array",
                            "items": {
                                "allOf": [
                                    {
                                        "$ref": "#/definitions/dto.Resource"
                                    },
                                    {
                                        "type": "object",
                                        "properties": {
                                            "body": {
                                                "type": "object",
                                                "additionalProperties": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                ]
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid input\" example={\"error\":\"shard_ids is required\"}",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Server error\" example={\"error\":\"Failed to list pending resources: database error\"}",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.Resource": {
            "type": "object",
            "required": [
                "shard_id"
            ],
            "properties": {
                "body": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "current_version": {
                    "type": "integer"
                },
                "kind": {
                    "type": "string"
                },
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "resource_group": {
                    "type": "string"
                },
                "shard_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "dto.ResourceCreateOpts": {
            "type": "object",
            "required": [
                "shard_id"
            ],
            "properties": {
                "body": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "kind": {
                    "type": "string"
                },
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "resource_group": {
                    "type": "string"
                },
                "shard_id": {
                    "type": "string"
                }
            }
        },
        "dto.ResourceUpdateOpts": {
            "type": "object",
            "required": [
                "shard_id"
            ],
            "properties": {
                "body": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "current_version": {
                    "type": "integer"
                },
                "kind": {
                    "type": "string"
                },
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "resource_group": {
                    "type": "string"
                },
                "shard_id": {
                    "type": "string"
                },
                "without_up_version": {
                    "type": "boolean"
                }
            }
        },
        "http.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
