{{- if or (.Values.postgresql.enabled) (and (.Values.externalPostgresql.url) (not .Values.externalPostgresql.existingSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "state-manager.fullname" . }}-postgresql
  labels:
    {{- include "state-manager.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.configuration.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if and (not .Values.postgresql.enabled) (and (.Values.externalPostgresql.url) (not .Values.externalPostgresql.existingSecret)) }}
    {{- with .Values.externalPostgresql.secretAnnotations }}
       {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
data:
  DATABASE_URL: {{ include "state-manager.postgresql.endpoint" . | quote }}
{{- end }}
