/*
No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the InternalHttpErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InternalHttpErrorResponse{}

// InternalHttpErrorResponse struct for InternalHttpErrorResponse
type InternalHttpErrorResponse struct {
	Error *string `json:"error,omitempty"`
}

// NewInternalHttpErrorResponse instantiates a new InternalHttpErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInternalHttpErrorResponse() *InternalHttpErrorResponse {
	this := InternalHttpErrorResponse{}
	return &this
}

// NewInternalHttpErrorResponseWithDefaults instantiates a new InternalHttpErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInternalHttpErrorResponseWithDefaults() *InternalHttpErrorResponse {
	this := InternalHttpErrorResponse{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *InternalHttpErrorResponse) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalHttpErrorResponse) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *InternalHttpErrorResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *InternalHttpErrorResponse) SetError(v string) {
	o.Error = &v
}

func (o InternalHttpErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InternalHttpErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableInternalHttpErrorResponse struct {
	value *InternalHttpErrorResponse
	isSet bool
}

func (v NullableInternalHttpErrorResponse) Get() *InternalHttpErrorResponse {
	return v.value
}

func (v *NullableInternalHttpErrorResponse) Set(val *InternalHttpErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableInternalHttpErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableInternalHttpErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInternalHttpErrorResponse(val *InternalHttpErrorResponse) *NullableInternalHttpErrorResponse {
	return &NullableInternalHttpErrorResponse{value: val, isSet: true}
}

func (v NullableInternalHttpErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInternalHttpErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


