/*
No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stateclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InternalHttpCreateResourceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InternalHttpCreateResourceRequest{}

// InternalHttpCreateResourceRequest struct for InternalHttpCreateResourceRequest
type InternalHttpCreateResourceRequest struct {
	Annotations *map[string]string `json:"annotations,omitempty"`
	Finalizers []string `json:"finalizers,omitempty"`
	Labels *map[string]string `json:"labels,omitempty"`
	Name string `json:"name"`
	ShardId string `json:"shard_id"`
	Spec []int32 `json:"spec,omitempty"`
}

type _InternalHttpCreateResourceRequest InternalHttpCreateResourceRequest

// NewInternalHttpCreateResourceRequest instantiates a new InternalHttpCreateResourceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInternalHttpCreateResourceRequest(name string, shardId string) *InternalHttpCreateResourceRequest {
	this := InternalHttpCreateResourceRequest{}
	this.Name = name
	this.ShardId = shardId
	return &this
}

// NewInternalHttpCreateResourceRequestWithDefaults instantiates a new InternalHttpCreateResourceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInternalHttpCreateResourceRequestWithDefaults() *InternalHttpCreateResourceRequest {
	this := InternalHttpCreateResourceRequest{}
	return &this
}

// GetAnnotations returns the Annotations field value if set, zero value otherwise.
func (o *InternalHttpCreateResourceRequest) GetAnnotations() map[string]string {
	if o == nil || IsNil(o.Annotations) {
		var ret map[string]string
		return ret
	}
	return *o.Annotations
}

// GetAnnotationsOk returns a tuple with the Annotations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalHttpCreateResourceRequest) GetAnnotationsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Annotations) {
		return nil, false
	}
	return o.Annotations, true
}

// HasAnnotations returns a boolean if a field has been set.
func (o *InternalHttpCreateResourceRequest) HasAnnotations() bool {
	if o != nil && !IsNil(o.Annotations) {
		return true
	}

	return false
}

// SetAnnotations gets a reference to the given map[string]string and assigns it to the Annotations field.
func (o *InternalHttpCreateResourceRequest) SetAnnotations(v map[string]string) {
	o.Annotations = &v
}

// GetFinalizers returns the Finalizers field value if set, zero value otherwise.
func (o *InternalHttpCreateResourceRequest) GetFinalizers() []string {
	if o == nil || IsNil(o.Finalizers) {
		var ret []string
		return ret
	}
	return o.Finalizers
}

// GetFinalizersOk returns a tuple with the Finalizers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalHttpCreateResourceRequest) GetFinalizersOk() ([]string, bool) {
	if o == nil || IsNil(o.Finalizers) {
		return nil, false
	}
	return o.Finalizers, true
}

// HasFinalizers returns a boolean if a field has been set.
func (o *InternalHttpCreateResourceRequest) HasFinalizers() bool {
	if o != nil && !IsNil(o.Finalizers) {
		return true
	}

	return false
}

// SetFinalizers gets a reference to the given []string and assigns it to the Finalizers field.
func (o *InternalHttpCreateResourceRequest) SetFinalizers(v []string) {
	o.Finalizers = v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *InternalHttpCreateResourceRequest) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalHttpCreateResourceRequest) GetLabelsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *InternalHttpCreateResourceRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *InternalHttpCreateResourceRequest) SetLabels(v map[string]string) {
	o.Labels = &v
}

// GetName returns the Name field value
func (o *InternalHttpCreateResourceRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *InternalHttpCreateResourceRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *InternalHttpCreateResourceRequest) SetName(v string) {
	o.Name = v
}

// GetShardId returns the ShardId field value
func (o *InternalHttpCreateResourceRequest) GetShardId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ShardId
}

// GetShardIdOk returns a tuple with the ShardId field value
// and a boolean to check if the value has been set.
func (o *InternalHttpCreateResourceRequest) GetShardIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShardId, true
}

// SetShardId sets field value
func (o *InternalHttpCreateResourceRequest) SetShardId(v string) {
	o.ShardId = v
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *InternalHttpCreateResourceRequest) GetSpec() []int32 {
	if o == nil || IsNil(o.Spec) {
		var ret []int32
		return ret
	}
	return o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalHttpCreateResourceRequest) GetSpecOk() ([]int32, bool) {
	if o == nil || IsNil(o.Spec) {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *InternalHttpCreateResourceRequest) HasSpec() bool {
	if o != nil && !IsNil(o.Spec) {
		return true
	}

	return false
}

// SetSpec gets a reference to the given []int32 and assigns it to the Spec field.
func (o *InternalHttpCreateResourceRequest) SetSpec(v []int32) {
	o.Spec = v
}

func (o InternalHttpCreateResourceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InternalHttpCreateResourceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Annotations) {
		toSerialize["annotations"] = o.Annotations
	}
	if !IsNil(o.Finalizers) {
		toSerialize["finalizers"] = o.Finalizers
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	toSerialize["name"] = o.Name
	toSerialize["shard_id"] = o.ShardId
	if !IsNil(o.Spec) {
		toSerialize["spec"] = o.Spec
	}
	return toSerialize, nil
}

func (o *InternalHttpCreateResourceRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"shard_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInternalHttpCreateResourceRequest := _InternalHttpCreateResourceRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInternalHttpCreateResourceRequest)

	if err != nil {
		return err
	}

	*o = InternalHttpCreateResourceRequest(varInternalHttpCreateResourceRequest)

	return err
}

type NullableInternalHttpCreateResourceRequest struct {
	value *InternalHttpCreateResourceRequest
	isSet bool
}

func (v NullableInternalHttpCreateResourceRequest) Get() *InternalHttpCreateResourceRequest {
	return v.value
}

func (v *NullableInternalHttpCreateResourceRequest) Set(val *InternalHttpCreateResourceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInternalHttpCreateResourceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInternalHttpCreateResourceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInternalHttpCreateResourceRequest(val *InternalHttpCreateResourceRequest) *NullableInternalHttpCreateResourceRequest {
	return &NullableInternalHttpCreateResourceRequest{value: val, isSet: true}
}

func (v NullableInternalHttpCreateResourceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInternalHttpCreateResourceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


