/*
No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stateclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateResourceStatusRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateResourceStatusRequest{}

// UpdateResourceStatusRequest struct for UpdateResourceStatusRequest
type UpdateResourceStatusRequest struct {
	Annotations *map[string]string `json:"annotations,omitempty"`
	CurrentVersion *int32 `json:"current_version,omitempty"`
	Labels *map[string]string `json:"labels,omitempty"`
	ShardId string `json:"shard_id"`
	Status map[string]interface{} `json:"status,omitempty"`
	Version *int32 `json:"version,omitempty"`
}

type _UpdateResourceStatusRequest UpdateResourceStatusRequest

// NewUpdateResourceStatusRequest instantiates a new UpdateResourceStatusRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateResourceStatusRequest(shardId string) *UpdateResourceStatusRequest {
	this := UpdateResourceStatusRequest{}
	this.ShardId = shardId
	return &this
}

// NewUpdateResourceStatusRequestWithDefaults instantiates a new UpdateResourceStatusRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateResourceStatusRequestWithDefaults() *UpdateResourceStatusRequest {
	this := UpdateResourceStatusRequest{}
	return &this
}

// GetAnnotations returns the Annotations field value if set, zero value otherwise.
func (o *UpdateResourceStatusRequest) GetAnnotations() map[string]string {
	if o == nil || IsNil(o.Annotations) {
		var ret map[string]string
		return ret
	}
	return *o.Annotations
}

// GetAnnotationsOk returns a tuple with the Annotations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateResourceStatusRequest) GetAnnotationsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Annotations) {
		return nil, false
	}
	return o.Annotations, true
}

// HasAnnotations returns a boolean if a field has been set.
func (o *UpdateResourceStatusRequest) HasAnnotations() bool {
	if o != nil && !IsNil(o.Annotations) {
		return true
	}

	return false
}

// SetAnnotations gets a reference to the given map[string]string and assigns it to the Annotations field.
func (o *UpdateResourceStatusRequest) SetAnnotations(v map[string]string) {
	o.Annotations = &v
}

// GetCurrentVersion returns the CurrentVersion field value if set, zero value otherwise.
func (o *UpdateResourceStatusRequest) GetCurrentVersion() int32 {
	if o == nil || IsNil(o.CurrentVersion) {
		var ret int32
		return ret
	}
	return *o.CurrentVersion
}

// GetCurrentVersionOk returns a tuple with the CurrentVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateResourceStatusRequest) GetCurrentVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.CurrentVersion) {
		return nil, false
	}
	return o.CurrentVersion, true
}

// HasCurrentVersion returns a boolean if a field has been set.
func (o *UpdateResourceStatusRequest) HasCurrentVersion() bool {
	if o != nil && !IsNil(o.CurrentVersion) {
		return true
	}

	return false
}

// SetCurrentVersion gets a reference to the given int32 and assigns it to the CurrentVersion field.
func (o *UpdateResourceStatusRequest) SetCurrentVersion(v int32) {
	o.CurrentVersion = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *UpdateResourceStatusRequest) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateResourceStatusRequest) GetLabelsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *UpdateResourceStatusRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *UpdateResourceStatusRequest) SetLabels(v map[string]string) {
	o.Labels = &v
}

// GetShardId returns the ShardId field value
func (o *UpdateResourceStatusRequest) GetShardId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ShardId
}

// GetShardIdOk returns a tuple with the ShardId field value
// and a boolean to check if the value has been set.
func (o *UpdateResourceStatusRequest) GetShardIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShardId, true
}

// SetShardId sets field value
func (o *UpdateResourceStatusRequest) SetShardId(v string) {
	o.ShardId = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *UpdateResourceStatusRequest) GetStatus() map[string]interface{} {
	if o == nil || IsNil(o.Status) {
		var ret map[string]interface{}
		return ret
	}
	return o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateResourceStatusRequest) GetStatusOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Status) {
		return map[string]interface{}{}, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *UpdateResourceStatusRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given map[string]interface{} and assigns it to the Status field.
func (o *UpdateResourceStatusRequest) SetStatus(v map[string]interface{}) {
	o.Status = v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *UpdateResourceStatusRequest) GetVersion() int32 {
	if o == nil || IsNil(o.Version) {
		var ret int32
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateResourceStatusRequest) GetVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *UpdateResourceStatusRequest) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int32 and assigns it to the Version field.
func (o *UpdateResourceStatusRequest) SetVersion(v int32) {
	o.Version = &v
}

func (o UpdateResourceStatusRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateResourceStatusRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Annotations) {
		toSerialize["annotations"] = o.Annotations
	}
	if !IsNil(o.CurrentVersion) {
		toSerialize["current_version"] = o.CurrentVersion
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	toSerialize["shard_id"] = o.ShardId
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

func (o *UpdateResourceStatusRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"shard_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateResourceStatusRequest := _UpdateResourceStatusRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateResourceStatusRequest)

	if err != nil {
		return err
	}

	*o = UpdateResourceStatusRequest(varUpdateResourceStatusRequest)

	return err
}

type NullableUpdateResourceStatusRequest struct {
	value *UpdateResourceStatusRequest
	isSet bool
}

func (v NullableUpdateResourceStatusRequest) Get() *UpdateResourceStatusRequest {
	return v.value
}

func (v *NullableUpdateResourceStatusRequest) Set(val *UpdateResourceStatusRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateResourceStatusRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateResourceStatusRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateResourceStatusRequest(val *UpdateResourceStatusRequest) *NullableUpdateResourceStatusRequest {
	return &NullableUpdateResourceStatusRequest{value: val, isSet: true}
}

func (v NullableUpdateResourceStatusRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateResourceStatusRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


