apiVersion: v2
name: state-manager
description: Helm Chart for deploying to Kubernetes of service state-manager 
  as a part of reconcile-kit 
type: application
version: 0.1.0
appVersion: "v0.0.6"
dependencies:
- condition: redis-ha.enabled
  name: redis-ha
  repository: https://dandydeveloper.github.io/charts/
  version: 4.33.2
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 15.x.x